name: tummy_tap
description: TummyTap delivery app frontend (MVP)
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.5.0
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  google_maps_flutter: ^2.6.0
  flutter_map: ^8.0.0
  latlong2: ^0.9.1 
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  intl: ^0.19.0
  flutter_animate: ^4.5.0
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.2.1
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
