# Generated by Django 5.2.5 on 2025-09-01 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.CharField(blank=True, help_text='Mobile number in international format, e.g. +911234567890', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
