# Generated by Django 5.2.5 on 2025-09-01 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_address_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='mobile',
            field=models.CharField(default='0000000000', help_text='Mobile number in international format, e.g. +911234567890', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number', regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
    ]
