# Generated by Django 5.2.5 on 2025-09-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('gpay', 'Google Pay'), ('upi', 'UPI')], default='cod', max_length=20),
        ),
    ]
